# Generated by Django 5.2.8 on 2025-11-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('org_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('org_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
