# Generated by Django 5.2.8 on 2025-11-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='primary_goal',
            field=models.TextField(default='Default goal'),
        ),
    ]
