# Generated by Django 5.2.8 on 2025-11-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partnership_primary_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='primary_goal',
            field=models.CharField(default='Default goal', max_length=200),
        ),
    ]
