# Generated by Django 5.2.8 on 2025-11-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_partnership_primary_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='org_type',
            field=models.CharField(default='Other', max_length=200),
        ),
    ]
